export const FETCH_GITHUB_SEARCH_USER_LOADING = 'FETCH_GITHUB_SEARCH_USER_LOADING';
export const FETCH_GITHUB_SEARCH_USER_FAILURE = 'FETCH_GITHUB_SEARCH_USER_FAILURE';
export const FETCH_GITHUB_SEARCH_USER_SUCCESS = 'FETCH_GITHUB_SEARCH_USER_SUCCESS';

export const FETCH_GITHUB_USER_FOLLOWERS_LOADING = 'FETCH_GITHUB_USER_FOLLOWERS_LOADING';
export const FETCH_GITHUB_USER_FOLLOWERS_FAILURE = 'FETCH_GITHUB_USER_FOLLOWERS_FAILURE';
export const FETCH_GITHUB_USER_FOLLOWERS_SUCCESS = 'FETCH_GITHUB_USER_FOLLOWERS_SUCCESS';
