export const FETCH_GITHUB_SEARCH_USER_LOADING = 'FETCH_GITHUB_SEARCH_USER_LOADING';
export const FETCH_GITHUB_SEARCH_USER_FAILURE = 'FETCH_GITHUB_SEARCH_USER_FAILURE';
export const FETCH_GITHUB_SEARCH_USER_SUCCESS = 'FETCH_GITHUB_SEARCH_USER_SUCCESS';